### ISSUE TITLE
INSTALL.md Modifications for Mac OS

### ISSUE THREAD

**Issue by megandalster** [DickinsonCollege/FarmData2#101]
FarmData2 can be more easily installed for development on Mac OS when the attached modifications are made to INSTALL.md. 
<img width="1030" alt="farmdata2 macOS install dev notes1" src="https://user-images.githubusercontent.com/4589017/104376043-5e8c3d80-54f2-11eb-9c50-b384ccc9fc48.png">
<img width="822" alt="farmdata2 macOS install dev notes2" src="https://user-images.githubusercontent.com/4589017/104376054-6350f180-54f2-11eb-81c5-8859f3e2b35c.png">
<img width="933" alt="farmdata2 macOS install dev notes3" src="https://user-images.githubusercontent.com/4589017/104376057-65b34b80-54f2-11eb-9c10-ff67d641bf91.png">
<img width="818" alt="farmdata2 macOS install dev notes4" src="https://user-images.githubusercontent.com/4589017/104376063-68ae3c00-54f2-11eb-9028-aabcab1f2636.png">

**Comment by braughtg** [comment]
Let's think about how to offset OS specific comments in the INSTALL.md document in a way that they are there but do not get in the the way.   Maybe we could use a table like:

__OS__ |  |
---|---|
MacOS |  Start docker and increase its memory resource to 4GB
Windows | blah blah

Or a block quote like:

> MacOS:  Start docker and increase its memory resource to 4GB
