### ISSUE TITLE
Note on pulling from upstream: database impact

### ISSUE THREAD

**Issue by megandalster** [DickinsonCollege/FarmData2#111]
When updating the code by pulling from upstream to your development instance of FarmData2, your database may need to be updated as well.  That is, you may need to remove the current docker/db folder and regenerate it by extracting the file db.tar.bz2 in the docker folder.

**Comment by braughtg** [comment]
Related to #80

**Comment by braughtg** [comment]
There is an open discussion on this topic on Zulip: 

https://farmdata2.zulipchat.com/#narrow/stream/271292-developers/topic/Handling.20db.20Updates

**Comment by braughtg** [comment]
There is now a setdb.bash script that simplifies the process.  However, if the sample db has been updated it is still necessary to know you have to run the setdb.bash script.  More thought could still be given to how to handle that,

**Comment by braughtg** [comment]
Once PR #569 is merged, a good possibility for how to handle this will be by versioning the volume used for the database in the docker-compose.yml file.  This would be like what is done for the home directory in the dev container.  That would ensure that we can force the creation of a new db volume each time there is an update to the db.

The challenge will be to have some script could detect that the db does not yet exist and expanding the sample database?  One possible way to do it would be to have a special container just for checking and creating that volume. That container could be used in the fd2-up.bash script to check and if necessary create the volume and expand the database.
