### ISSUE TITLE
Seedings Report: delete total row/bed planted

### ISSUE THREAD

**Issue by IrisSC** [DickinsonCollege/FarmData2#260]
The Direct Seeding Summary table that appears at the bottom of a Seeding Report contains a line for Total Row/Bed Planted. This metric not useful for farmers and clutters up the summary. Currently the summary table includes the Total Row/Bed Planted line which should be deleted:

![image](https://user-images.githubusercontent.com/16962482/144901625-03318ed5-fc2e-488b-b560-d7c45cde752b.png)

To test this:

1. Go to the Seeding Report subtab under the BarnKit tab
2. Enter a start and end date for a report (any date window with direct seedings will be sufficient)
3. Generate the report
4. Examine the Direct Seeding Summary table at the bottom of the page. 

The desired result will be similar to the following, where the Total Row/Bed Planted line has been removed:
![image](https://user-images.githubusercontent.com/16962482/144900603-bfaf3c82-d951-4a3f-8835-a4a51f37063f.png)

**Comment by braughtg** [comment]
Be sure to also remove any computed properties that are used to generate the value that appears here as well as any Cypress tests that check this value.

**Comment by JingyuMarcelLee** [comment]
I will work on this issue.
