### ISSUE TITLE
Seeding Report - Cypress Tests for Loading Spinner

### ISSUE THREAD

**Issue by josieecook** [DickinsonCollege/FarmData2#270]
Tests should be added to the seeding report page cypress test file for the loading spinner. These tests would ensure that it appears and disappears when appropriate.

Should test that:
* The spinner is shown on the page when an API call has been made
* The spinner remains on the page until the whole response has been returned
* The spinner disappears once the whole response has been returned
* The spinner reappears when new dates are selected and a new API call is made. (See Issue #272)

**Comment by braughtg** [comment]
For testing that the "whole response has been returned"  maybe test with a one page (one API request) response  and a two page response.  Use the date range to select only a few records for the one page response and a wider date range to select enough records so that it will require two API requests to get the data.  You can probably use a check in the Cypress tests for the number of rows in the report table to know when the full report has loaded.

**Comment by Batese2001** [comment]
How many records are in one api call? 

Also, I think I may still be confused on how to check that the spinner remains for the whole duration between the button being clicked and the api returning completely, as is specified in the second bullet point above.

I can check if the spinner is gone by the time the one and two page requests are done  by using the number of table rows but I cannot seem to figure out how to check if it is there just before. My attempts at finding a way to loop that have been unsuccessful thus far (one crashed cypress).

**Comment by braughtg** [comment]
> How many records are in one api call?
This depends on the length of the data in the responses.  My suggestion would be to use Hoppscotch to make some requests and look at the top of the response to see how many pages there are.  If you do a small range of just a few days it will likely fit in a one page response.  Then expand the date range until it rolls over into a second page.  

> Also, I think I may still be confused on how to check that the spinner remains for the whole duration between the button being clicked and the api returning completely, as is specified in the second bullet point above.
> 
> I can check if the spinner is gone by the time the one and two page requests are done by using the number of table rows but I cannot seem to figure out how to check if it is there just before. My attempts at finding a way to loop that have been unsuccessful thus far (one crashed cypress).

Can you check that the spinner is there right after the test clicks the generate report button?  Then for the 1 page response, check that it is gone when the right number of rows are in the table?  If that works then for the 2 page response you could check that the spinner is there after the first page rows are added and before the second page rows are added, and then finally that it is gone when both pages have been loaded.

**Comment by Batese2001** [comment]
I see what you mean, though it seems that the getAllPages function always ends up getting all of its pages and putting them in the array and before I can test it. I have it check for the table as soon as it appears but it always has the correct end amount of rows, as opposed to having only one page of results and then the next. 
I can see in the cypress log on the side that it sends the request, gets the request back, starts searching for the table, gets the second page of the request, finds the table and then the row number, thus checking a value that I do not want yet.
