### ISSUE TITLE
Seeding Report - Loading spinner should reappear when new dates selected

### ISSUE THREAD

**Issue by josieecook** [DickinsonCollege/FarmData2#272]
The loading spinner currently only appears during the first API call after the seeding report page loads. It does not reappear whenever new dates are selected and a new API call is made.

This is the spinner with the desired behavior:
![spinner](https://user-images.githubusercontent.com/60167626/126837529-61d4baf0-a8d2-4752-961d-ea1d9f0fa956.png)

The seeding report page should be edited so that the spinner appears whenever any new API call is made, not just the first call.

Cypress tests should be added for this behavior, see Issue #270

**Comment by Batese2001** [comment]
I will start work on this so that error #258 may progress
