### ISSUE TITLE
Seeding Input: restructure order of Inputs

### ISSUE THREAD

**Issue by IrisSC** [DickinsonCollege/FarmData2#273]
The Data section should be broken up into two sections, with the date, crop, comments, and area in the first section. The second section should have everything else and be after the Tray/Direct Seeding section. The second section should be called something other than data.

![reorderingDataInputs](https://user-images.githubusercontent.com/54850069/126838199-a64fda69-909c-4c40-902a-c0ed3a6990e6.png)

To test this go to the Seedings Input subtab under FieldKit tab, which is on the home page.  

The code can be found by going to farmdata2_modules/fd2_tabs/fd2_field_kit/seedingInput.html file.

**Comment by braughtg** [comment]
It appeared that some of this reordering was in PR #263 as well.  There is still work to be done here as described in the discussion on PR #281, so I'll leave this open until that is closed.
