### ISSUE TITLE
Seeding Report Page - Fix timing of report disappearing when new dates selected

### ISSUE THREAD

**Issue by josieecook** [DickinsonCollege/FarmData2#274]
The seeding report page hides everything but the date selection section when new dates are being chosen. Currently, the rest of the page disappears once the input has been changed and then clicked off of, instead of right after the initial click.
![datechange](https://user-images.githubusercontent.com/60167626/126838291-d55f1996-db67-470e-9f2d-95101175e777.png)

There are two possible solutions:
* Change the page to hide the report right after the user does an initial click on the date inputs
* Add a "Change Date Range" button that, when clicked, hides the rest of the page and allows the user to input new dates.

**Comment by Batese2001** [comment]
I'll start work on this
