### ISSUE TITLE
Cache Area/Crop Lists for Seeding Inputs

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#278]
Explore ways to possibly cache the area and crop lists for the seeing input form.  It takes too long to retrieve these from the server every time the form is accessed.  
* It may be possible to improve the performance of this on the FarmOS/Drupal end.  This would require some research into the general performance of the API.  A search of the FarmOS forums and maybe a conversation with the devs on their chat platform would be a good place to start.  If this approach is viable then it would probably be the preferred approach since it would require no changes to the front end and would always ensure the most up to date data is available.
* Another possibility would be to retrieve and cache these lists the first time they are needed. This could be done in one of the Vue.js lifecycle hooks.  That hook could check if the needed values had been cached and if not make the API requests and cache the results. Then the dropdowns could be populated more quickly from the cached results.  The big question here is where those lists could be stored so that they persist across changes in tabs and sub-tabs, etc.  Again a question to the FarmOS community explaining that we'd like JS code running in a tab to be able to cache information so that it is available later, (i.e. after the tab is changed and then changed back).

**Comment by IrisSC** [comment]
Draft pull request is at #298
