### ISSUE TITLE
Reevaluate some cypress testing

### ISSUE THREAD

**Issue by Batese2001** [DickinsonCollege/FarmData2#296]
The cypress tests for the seeing report (farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.spec.js) fail in searching for some elements as seen here
![image](https://user-images.githubusercontent.com/69521504/136886841-7502ea47-b930-457e-ad9d-8a2369d56c1c.png)

As they are searching for an element that cannot exist, something must be wrong with the tests themselves, as the summaries appear to be working as intended

**Comment by braughtg** [comment]
See tests for the API sub tab of the FD2 Example (farmdata2_modules/fd2_tabs/fd2_example/api.spec.js) for an example of how to structure the tests. In particular, see the beforeEach hook and how it waits for page content to be loaded in the Vue mounted hook. Following that model should fix these issues.

**Comment by braughtg** [comment]
Superseded by #367.
