### ISSUE TITLE
Seeding Input Form UI Design

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#301]
Consider moving the Comment's field for the Seeding Input form on the Field Kit tab to the bottom of the form, in its own box.  Add a red heading "Comments" and have it just contain the comment box without its own label.  Comments will be rarely used. So moving this to the bottom will prevent having to scroll over that box while entering data for a planting.  It will still need to be scrolled over at the end to get to the submit button, but that will not be as disruptive to the workflow.

**Comment by braughtg** [comment]
Expand this issue to be a revisiting the layout of the components in the seeding input form.  Moving the comment box is one such change that should be made.  Others include conciseness of the language used and the location of components (e.g. having them appear on the same line, eliminating unnecessary labels, etc).

**Comment by JingyuMarcelLee** [comment]
I will work on it too
