### ISSUE TITLE
Rename DropdownWithAll defaultInput prop

### ISSUE THREAD

**Issue by Batese2001** [DickinsonCollege/FarmData2#321]
The defaultInput ~and defaultDate~ props within the DropdownWithAllComponent ~and DateSelectionComponent are~ is not well named given the addition of #320 - which enables changes in the prop to set the selected value.  Thus, it is now more apt to call it something like "selection" or "selectedVal" etc. This would require renaming this in the component and everywhere it is used

**Comment by braughtg** [comment]
When this change is made it will be important to also update the associated documentation in the README.md in https://github.com/DickinsonCollege/FarmData2/tree/main/farmdata2_modules/fd2_tabs/resources

**Comment by FutzMonitor** [comment]
I will be tackling this issue.
