### ISSUE TITLE
Seeding Input: Takes invalid(negative) input values

### ISSUE THREAD

**Issue by JingyuMarcelLee** [DickinsonCollege/FarmData2#323]
On the Seeding Input form on the FieldKit tab, negative input values can be taken. A seeding report can be generated with these values. 

**Steps to replicate**

1. Visit the Seeding Input sub-tab of the FieldKit tab
2. Choose the crop and area for seeding
3. Select the Seeding method. 
4. Submit button has been activated. Click to generate the report.

![bug1](https://user-images.githubusercontent.com/46755208/145281662-11189418-9b86-4995-8842-af0a4c73e240.PNG)

This will generate a seeding report with negative values.

![bug2](https://user-images.githubusercontent.com/46755208/145281786-7d52f33a-24c5-4f54-b862-a48ccaef7965.PNG)

**Desired Behavior**

When negative input values are chosen for Seeding Input, the submit button should remain deactivated, throwing a message indicating an invalid input. Also, the report should invalidate any negative inputs, so the calculation of total values at the end of the report does not contain invalid values.

**Comment by braughtg** [comment]
Nice bug report.  This identifies the same issue at #333, which also highlights an issue with decimal values for some fields.  This issue will be closed and referenced from that one.
