### ISSUE TITLE
Suspicious Behavior: Invalid input values entered

### ISSUE THREAD

**Issue by JuheonChu** [DickinsonCollege/FarmData2#324]
![190Q06Negative](https://user-images.githubusercontent.com/35699839/145304916-7a6f8fe4-527a-4467-a41f-5ea45591f86c.png)

While running a Dickinson Farm application, A seeding report can be generated with the invalid input values on the tab of FieldKit tab from the Seeding Input Form. 

**Steps to replicate**
1. Go to the Seeding Input tab which is a sub-tab of Field Kit tab 
2. Fill out all the blanks for the Data Section
3. Choose which way do you want to seed
4. Put the invalid input values and from the checkBoxes and submit to generate the report

Notice that this will generate the Seeding Report with negative values of **work hours, labor hours, rows, and number of feets** as below

![190A14](https://user-images.githubusercontent.com/35699839/145395135-448ef897-4b2d-42bb-b942-7c9f4b552692.png)

**Desired/Observed Output**
1. They should not allow negative invalid inputs, which means clicking "down-arrow" button to negative values should be deactivated.
2. The total value should not accept any invalid outputs in any way, such as negative values.

**Comment by braughtg** [comment]
Nice bug report.  This identifies the same issue at #333, which also highlights an issue with decimal values for some fields.  This issue is being closed but will be referenced from that one.
