### ISSUE TITLE
Bad input: Possible to create Seeding Input record with invalid input

### ISSUE THREAD

**Issue by MeapBoi** [DickinsonCollege/FarmData2#325]
Creating a new Seeding Input record with invalid values on the FieldKit tab from the Seeding Input Form is possible.
**Steps to replicate:**
1. Access the Field Kit tab
2. Create a Seeding Input record
3. Fill out all the blanks for the Data Section
4. Choose the method of seeding
5. Put the invalid input values and from the checkBoxes 
![image](https://user-images.githubusercontent.com/77969945/145418153-f682babd-1a81-4f86-8246-576bab473c56.png)
6. Submit the invalid input to generate an invalid record
![image](https://user-images.githubusercontent.com/77969945/145418567-cd694c3d-7b9e-4c6a-87d7-f770b0191198.png)

**Desired output:**
1. Should not be allowed to create records from invalid input:
2. Deactivate the down value button when it reaches 0
3. Implement value checker for invalid input

**Comment by braughtg** [comment]
Nice bug report. This identifies the same issue as #333, which also highlights an issue with decimal values for some fields. This issue is being closed but will be referenced from that one.
