### ISSUE TITLE
Seeding Input Log: Allows Invalid Input

### ISSUE THREAD

**Issue by hailie-mitchell** [DickinsonCollege/FarmData2#326]
When creating a new Seeding Input Log, negative values are accepted in all numerical fields, including number of trays planted, cells per tray, number of seeds planted, workers, and time. 

<img width="515" alt="Seeding Log Input Bug Report" src="https://user-images.githubusercontent.com/76420146/145513808-0497e8d0-4793-49ef-8b81-eeaff8e9cf24.png">

To recreate bug:
1. Log in and click on Field Kit.
2. Click on Seeding Input from the top sub-tabs.
3. Fill in required fields, then fill in numerical fields with negative inputs.

Output should not allow negative input in the numerical fields, and the submit button should be greyed out to indicate that a seeding input cannot be submitted with invalid input. Currently, negative inputs are allowed and the user can submit a report with these inputs.

**Comment by braughtg** [comment]
Nice bug report. This identifies the same issue as #333, which also highlights an issue with decimal values for some fields. This issue is being closed but will be referenced from that one.
