### ISSUE TITLE
FieldKit: Seeding Input Log Accepts Negative Values

### ISSUE THREAD

**Issue by FutzMonitor** [DickinsonCollege/FarmData2#328]
The *Seeding Input Log* currently allows the user _manager_ to input negative values into the the different data boxes for the type of seeding and the labor involved in the process. This shouldn't be possible because it is illogical for a negative amount of labor and seeding to occur during a seeding log input. There should be some sort of check that prevents the report from being submitted if the code detects negative values in the labor and seeding sections of the Seeding Input Log.

![image](https://user-images.githubusercontent.com/31524934/145521504-fcf14d51-099d-4e7b-b456-cab7cfe47204.png)

#### Testing
1. Click on the FieldKit tab on the FarmData2 homepage
2. Click on the Seeding Input subtab 
3. Input whatever you'd like for the **Data** section of the Seeding Input Log
4. Now enter any negative value you'd like for the **Seeding** and **Labor** sections. 
5. Submit! The report will go through and even ask you if you'd like to see the report

The desired results would be similar to the following, where the page prevents the user from submitting the log unless they change the invalid values:

![image](https://user-images.githubusercontent.com/31524934/145522303-fdb9554c-bb6e-47b6-9cfb-65e8b10ffb6f.png)

**Comment by braughtg** [comment]
Nice bug report. This identifies the same issue as #333, which also highlights an issue with decimal values for some fields. This issue is being closed but will be referenced from that one.
