### ISSUE TITLE
Suspicious Behavior: Enter invalid values in Seeding Input record

### ISSUE THREAD

**Issue by cowfrica-1702** [DickinsonCollege/FarmData2#330]
![Screen Shot 2021-12-10 at 1 41 19 PM](https://user-images.githubusercontent.com/63311059/145625360-bb2f9bf3-254a-4d85-a681-fcb95c005750.png)

**Summary**
When creating a Seeding Input record, it is possible to enter invalid values. 

**Step to reproduce**
1. Open the application.
2. Go to the "FieldKit" tab.
3. Go to the "Seeding input" tab.
4. Enter the invalid value, such as negative numbers, in the Tray Seeding and Labor section. 
5. Click the "submit" button.

**Expected result**
There was no warning for the invalid input, and the user could still submit the result although the inputs are invalid.

**Comment by braughtg** [comment]
Nice bug report. This identifies the same issue as #333, which also highlights an issue with decimal values for some fields. This issue is being closed but will be referenced from that one.
