### ISSUE TITLE
Seeding Report: Incorrect Sorting Order

### ISSUE THREAD

**Issue by Tanman2001** [DickinsonCollege/FarmData2#331]
The seeding report appears to have the wrong sort order when there are both types of seedings (Tray Seedings and Direct Seedings) in the results. The desired sorting order should be by Type of Seeding (Tray/Direct) _then_ by date so that the earliest seeding is always at the top of the table and the latest always at the bottom. 

However, it appears the current sorting is by date then by Type of Seeding. So, at the moment, the earliest Direct Seeding is at the top followed by the rest of the Direct Seedings in order by date, then the earliest Tray Seeding followed by the rest of the Tray Seedings in order by date. As the latest Direct Seeding can be more recent than the earliest Tray Seeding, the table may not be in the desired order.

Using the sample database, we can see this by doing the following:
1. Go to BarnKit > Seeding Report to make a Seeding Report
2. Set "Start Date" to 5/20/2020
3. Set "End Date" to 7/10/2020
4. Click "Generate Report"
5. Scroll part-way through the table to see a Direct Seeding dated 7/10/2020 immediately followed by a Tray Seeding dated 5/22/2020.

![SortBug](https://user-images.githubusercontent.com/32078791/145643838-5c2cb3e6-b174-4c3b-a9f4-0d8c943f9073.PNG)

**Comment by braughtg** [comment]
Nice issue report.  As this reports on the same issue as #332, this one is being closed and that one will remain open.
