### ISSUE TITLE
Crop spelling error

### ISSUE THREAD

**Issue by goldberl** [DickinsonCollege/FarmData2#334]
**Description:** In the Seeding Input Log, one of the crop options **'RADDICCHIO' is misspelled with two D's**. It should be spelled 'RADICCHIO' with one D.

**Directions to Replicate the Bug**
1. Open the FarmData2 Application
2. Click on the Seeding Input button in the FieldKit Tab
3. Go to the 'Crop' section and scroll down until 'RADDICCHIO'

![image](https://user-images.githubusercontent.com/76408777/145693059-f1e5aaa1-52c7-4033-ba37-fa718c6d5669.png)

**Comment by braughtg** [comment]
Nice catch!!

The information contained in that dialog is generated from the Crops Vocabulary that is part of the sample data base distributed with the FarmData2 developer installation. The fix will require:
1. Editing the docker/sampleDB/sampleData/crops.csv file to correct the misspelling
2. Rebuild the sample database using the docker/sampleDB/buildSampleDB.bash script.

A PR to fix this issue should include:
1. The updated crops.csv file
2. A new db.sample.tar.bz2 file including the updated database.

**Comment by braughtg** [comment]
This may also require some modifications to the utils.py file that does translation of crop names if the misspelling exists in the original FarmData data that is being imported.   This would be flagged by errors about an unknown crop in the process of rebuilding the database.
