### ISSUE TITLE
License.md file: Authors.md link

### ISSUE THREAD

**Issue by goldberl** [DickinsonCollege/FarmData2#335]
**Description:** The Authors.md link in the Attribution section of the License.md file leads to an invalid GitHub page.

This may be related to Issue #14

**Comment by braughtg** [comment]
Good catch!  For now, it would be acceptable to remove the sentence mentioning the AUTHORS.md file.  Maybe it is possible to replace that link with one that points to a page in GitHub that lists all of the contributors?

Then when Issue #14 is resolved a link can be restored to that file in this location.
