### ISSUE TITLE
Seeding Input Log: Invalid Inputs

### ISSUE THREAD

**Issue by Liwen0127** [DickinsonCollege/FarmData2#337]
**Description of the issue**: The seeding input log currently accepts negative numbers such as numbers of seeds planted, number of workers, and labor time. The system allows invalid input to be added to the seeding log and to be formulated into a seeding report. 

**Steps to reproduce:**
1.	Login to FarmData2 website.
2.	Click on the FieldKit → Seeding Input 
3.	Choose the crop you want to plant.
4.	Pick an area you want to plant this crop in.
5.	Add a message in the comment box (or leave it blank).
6.	Click either Tray Seeding or Direct Seeding.
7.	Enter any negative number. 
8.	Click on Labor and enter any negative number or invalid number.
9.	Click Submit button

![1](https://user-images.githubusercontent.com/89795306/145731903-f4c6ca6b-598c-4fc9-b116-0d83c404b01a.png)

![2](https://user-images.githubusercontent.com/89795306/145731910-22c7a360-96ff-4291-9b47-4ba3503761f4.png)

**Expected Result**: The website should not allow the seeding input log to be created. It should give the user an error when selecting these invalid numbers and generate an error message when the user tries to submit this information.

**Observed/Actual Resul**t: The website offers invalid input in dropbox, allow users to manually type in invalid number, and allow users to submit invalid input to formulate a seeding report.

**Comment by braughtg** [comment]
Nice bug report. This identifies the same issue as #333, which also highlights an issue with decimal values for some fields. This issue is being closed but will be referenced from that one.
