### ISSUE TITLE
Seeding Input Log: Invalid Inputs Allowed

### ISSUE THREAD

**Issue by ethanhart2002** [DickinsonCollege/FarmData2#339]
## Description

When creating a Seeding Input Log in the **FieldKit** tab, it is possible to enter negative values for the **Rows per Bed, Number of Feet, Workers,** and **Time** fields in the log. Once negative values are entered, it is possible to click "Submit" and generate a Seeding Report that has negative values for the fields mentioned above.

#### Observed Seeding Input Log:

<img width="1440" alt="FarmDataObservedOutput" src="https://user-images.githubusercontent.com/69613592/145850040-a02ce3e3-9ec0-4ff1-ba6c-3c91e70bd934.png">

We see here that negative field values are allowed to be inputted, and that a **Seeding Report** is able to be generated because the **Submit** button can be clicked.

#### Observed Seeding Report:

<img width="793" alt="FarmDataReportObserved" src="https://user-images.githubusercontent.com/69613592/145850088-337bdb45-a391-4d8c-9a24-a4b1ee016c0d.png">

Here, a **Seeding Report** has been generated with negative values in the **Hours** and *Num Workers** fields of the report. 

## How to Repeat this Bug

1. Log in to FarmData2 with appropriate credentials, and open the **FieldKit** tab.
2. Select the **Seeding Input** tab on the **FieldKit** page.
3. For the section titled "Data", fill out each field as directed with any values.
4. For the sections titled "Tray Seeding/Direct Seeding" and "Labor", select either **Tray Seeding** or **Direct Seeding** and enter negative values for each field. Note that when each negative value is entered, it remains in the field without warning, and when all fields have been filled, it is possible to submit the **Seeding Input Log** as a **Seeding Report**. 
5. Submit the **Seeding Input Log** as a **Seeding Report**. In the new **Seeding Report** window, enter in the date used for the newly-filed **Seeding Input Log**. Generate the report, and examine the **Hours** and **Num Workers** fields. Note that these fields appear negative on the report. 

## Expected Output

<img width="797" alt="FarmDataExpected" src="https://user-images.githubusercontent.com/69613592/145852996-6d041d41-94d1-4794-8c61-2d3ee305ae2d.png">

In the dropdown buttons marked by the arrows, it should not be possible to click them to enter negative field values. Nor should it be possible to manually input negative field values in each field box.

**Comment by braughtg** [comment]
Really nice bug report. This identifies the same issue as #333, which also highlights an issue with decimal values for some fields. This issue is being closed but will be referenced from that one.
