### ISSUE TITLE
Seeding Input: invalid input allowed

### ISSUE THREAD

**Issue by maitnngo2002** [DickinsonCollege/FarmData2#340]
### Steps to replicate the error:
1. Log in using your account
2. Go to the FieldKit tab and click on the Seeding Input subtab
3.  Enter all the required information. For the **Tray/ Direct Seeding and Labor** section, choose values that are less than 0

![263756313_868330280520342_4484830047381537698_n](https://user-images.githubusercontent.com/63086003/145888430-7a6399cb-f588-49a1-b4c2-ebd402d9c849.png)

3. Submit and generate the report. You should see the invalid values that are displayed

### Observed output:

![258795122_412980920529550_8195076697034281722_n](https://user-images.githubusercontent.com/63086003/145888553-f1937a9b-566b-46c2-9954-edff2e55a5c6.png)

**Comment by braughtg** [comment]
Really nice bug report. This identifies the same issue as #333, which also highlights an issue with decimal values for some fields. This issue is being closed but will be referenced from that one.
