### ISSUE TITLE
Seeding input allows invalid values

### ISSUE THREAD

**Issue by elgueras** [DickinsonCollege/FarmData2#341]
# #Description: 
When anyone wants to create a new Seeding Input record, the Input log allows negative numbers to be inputed for things such as workers, time, cells per tray, number of seeds planted and number of trays planted. 

Steps to reproduce issue:
1. Login to FarmData2
2. Click on the FieldKit Tab
3. Click on Seeding Input
4. Fill out the date of Seeding, Crop, Area, and whether its a Tray Seeding or Direct Seeding
5. For the rest of the options (workers, time, cells per tray, number of seeds planted and number of trays planted) click the down button to enter negative numbers
6. Click submit
<img width="276" alt="Screenshot seeding Input" src="https://user-images.githubusercontent.com/76133531/146249075-0cde9afe-4d3e-4dde-9eb5-77b4f617cefb.png">

<img width="636" alt="Screenshot Seeding Report" src="https://user-images.githubusercontent.com/76133531/146249795-e0f0c6b2-a6a0-42e7-82be-2c824566c40c.png">

Expected Result:
The website should not allow invalid inputs in the dropdown menu and when invalid inputs are entered for the fields in the Seeding Input log a Seeding Report should not be generated, instead an error message should come up explaining that certain fields are invalid and need to be fixed before submitting. 

Observed Result: Allows users to type and manually enter invalid values and submit them to generate a Seeding Report.

**Comment by braughtg** [comment]
Really nice bug report. This identifies the same issue as #333, which also highlights an issue with decimal values for some fields. This issue is being closed but will be referenced from that one.
