### ISSUE TITLE
Seeding Input: Invalid Values Allowed

### ISSUE THREAD

**Issue by katiele47** [DickinsonCollege/FarmData2#342]
## Bug Description ##

The **Seeding Input** under the **FieldKit** tab accepts invalid inputs such as negative numbers and lets user generate the report with a clickable Submit button. This occurs when specifying quantities in **Tray Seeding/Direct Seeding** and **Labor** sections. 

#### Submit a Seeding Report with invalid values ####

1. Log in FarmData2 with `worker 1` (or `2`, `3`, `4`) credential
2. Go to **FieldKit** tab (to the right of the **FD2 Example** tab)
3. Select **Seeding Input** which prompts to the Seeding Input Log screen
4. Fill in the required fields under **Data** section
5. Select either **Direct Seeding** or **Tray Seeding** options
6. Fill in negative numbers
7. Under the Labor section, fill in negative numbers
8. Hit **Submit** to enter the report into the system

#### Generate the newly created report ####

1. Switch to **BarnKit** tab, and select **Seeding Report**
2. Enter the date range of the newly created report
3. Hit **Generate Report** to view the invalid report 

## Observed Output ##

The Seeding Input Log allows users to manually enter negative number, which generates an invalid report as the Submit button is clickable.

<img width="746" alt="Screen Shot 2021-12-15 at 4 40 04 PM" src="https://user-images.githubusercontent.com/54815905/146269888-aee52edd-d9f9-46ce-a48a-69154f137077.png">

<img width="994" alt="Screen Shot 2021-12-15 at 4 41 21 PM" src="https://user-images.githubusercontent.com/54815905/146269954-0ffa699b-062a-40e9-b1ec-a01c6ac544b8.png">

## Expected Output ##

The **Direct Seeding** /**Tray Seeding** and **Labor** sections in the Seeding Input Log should not allow user to manually enter the negative numbers. Using the Dropdown arrow selection should be the only available option when inserting new values. The submit button should also be disabled in such case.

**Comment by braughtg** [comment]
Really nice bug report. This identifies the same issue as #333, which also highlights an issue with decimal values for some fields. This issue is being closed but will be referenced from that one.
