### ISSUE TITLE
Seeding Report: Displays Incorrect Values

### ISSUE THREAD

**Issue by astern21** [DickinsonCollege/FarmData2#343]
Sometimes the Tray Seeding Summary table at the bottom of a **Seeding Report displays NaN**(Not a Number) instead of the proper values for the **“Total Number of Tray Seeds Planted”** and **“Average Seeds Planted per Hour”.** This only occurs on certain date ranges 

**Steps to reproduce bug:**

1. Click on BarnKit
2. Go to Seeding Report Sub-Tab
3. Select Start Date (01/01/2019) -> End Date (07/15/2020)
4. Scroll down to bottom of page and see Tray Seeding Summary table

![Screen Shot 2021-12-15 at 8 35 55 PM](https://user-images.githubusercontent.com/76089597/146292689-4041b1e2-603c-4332-8f76-6e44a8754329.png)

These are not the correct numbers but the desired result should be a number 

![Screen Shot 2021-12-15 at 8 54 28 PM](https://user-images.githubusercontent.com/76089597/146293692-ba49f5f7-107f-4c4d-a091-1e73ef229dae.png)

**Comment by braughtg** [comment]
Nice bug report.  This is also reported in issue #338 which provides a narrower date range for reproducing the issue.  That may help in tracking it down.  I will close this issue, but it will be referenced from that one.
