### ISSUE TITLE
Seeding Report: Allows Invalid Inputs

### ISSUE THREAD

**Issue by anlai46** [DickinsonCollege/FarmData2#344]
**Description: Users are able to enter invalid inputs such as negative values into the Seeding Input Log of FieldKit** 

**Steps to replicate this problem:**

1. Log into FarmData2 with the correct user credentials
2. Click on the tab FieldKit and then click on Seeding Input
3. Under the label "Labor" fill in a negative value for workers and time
4. Click submit and Generate Report

**Observed Output**

<img width="661" alt="image" src="https://user-images.githubusercontent.com/76227777/146338442-858cb93b-6f1d-4fec-b05b-4942d45b9857.png">

**Desired Output**

There should not be a bottom error option available to click to generate a negative value.

**Comment by braughtg** [comment]
Really nice bug report. This identifies the same issue as #333, which also highlights an issue with decimal values for some fields. This issue is being closed but will be referenced from that one.
