### ISSUE TITLE
FieldKit - Seeding Input Log: Negative Value Input Allowed

### ISSUE THREAD

**Issue by s017274** [DickinsonCollege/FarmData2#345]
### Problem:

In the FieldKit tab's Seeding Input Log, the user is able to enter invalid negative values for each numerical category (this includes "Number of Trays Planted", "Cells per Tray", and "Number of Seeds Planted" in the Tray Seeding menu, "Rows per Bed" and "Number of Feet" in the Direct Seeding menu, and "Workers" and "Time" in the Labor menu).

### Reproduce:

To reproduce this bug, starting from the **FarmData2 dashboard**:

**1. Select the FieldKit tab** 

![Screen Shot 2021-12-16 at 6 24 40 PM](https://user-images.githubusercontent.com/59842059/146468564-60a8a518-d258-4453-89fd-bc0e4a1eeadc.png)

**2. Select the Seeding Input Log**

![Screen Shot 2021-12-16 at 6 24 40 PM](https://user-images.githubusercontent.com/59842059/146468775-d961c973-c0a6-464e-8266-5b867fd8d2f8.png)

**3. Select either "Tray Seeding" or "Direct Seeding" and input a negative value in any numeric field in the Input Log.**

![Screen Shot 2021-12-16 at 6 23 17 PM](https://user-images.githubusercontent.com/59842059/146469084-be89c273-730f-4720-9222-50607bfe6237.png)

**Negative values should not be allowed in the Seeding Input Log, since none of the numeric input categories can realistically be negative numbers.** 

### Observed vs. Expected:

**Observed result**: The user is able to enter and submit negative values in the numerical categories in the Seeding Input Log, as shown below:

![Screen Shot 2021-12-16 at 6 23 33 PM](https://user-images.githubusercontent.com/59842059/146469110-68e0fd82-7d2a-414f-921b-8d2db24dcd86.png)

**Expected Result**: The Seeding Input Log will not allow negative numbers to be entered by the user, fixing the lowest possible value at 0. The user should be prevented from submitting the log until realistic (i.e., positive) numbers are entered. When the user attempts to enter negative numbers, the log should simply continue to display 0, and the "Submit" button should be inactive.

![Screen Shot 2021-12-16 at 6 24 10 PM](https://user-images.githubusercontent.com/59842059/146469283-6a25af0d-c91f-4155-977b-dd803c094f9b.png)

### Fix:

This bug will be fixed when the user can no longer input negative or otherwise impossible values into the Seeding Input Log and submit it.

**Comment by braughtg** [comment]
Really nice bug report.  This identifies the same issue as #333, which also highlights an issue with decimal values for some fields.  This issue is being closed but will be referenced from that one.
