### ISSUE TITLE
FieldKit's SeedingInput allows for the input of negative values

### ISSUE THREAD

**Issue by gfr4d3a2** [DickinsonCollege/FarmData2#346]
FieldKit's SeedingInput is where one inputs new entries for seeding events. The relevant fields are
* The number of workers
* The time taken
* Tray Seeding
  * Number of trays planted
  * Cells per tray
  * Number of seeds planted
* Direct Seeding
  * Rows per bed
  * Number of feet

All of these values should be positive, as it would be particularly strange for a negative number of workers to be planting a negative number of rows per bed for a number of negative feet during a duration of negative minutes. 

To reproduce, navigate to http://farmdatainstall/farm/fd2-field-kit/seedingInput as a logged in user with the privilege to add a new SeedingInput. Then, attempt to enter a negative number into the interface and submit. This should fail, but it is accepted.

Inputs being accepted HTML-side:
![image](https://user-images.githubusercontent.com/96209881/146513540-03e3cd3a-c948-467b-a384-43527de6525d.png)

Inputs being accepted server-side:
![image](https://user-images.githubusercontent.com/96209881/146513852-93df5881-57d7-4e80-b715-859512d22a99.png)

To fix this, two changes are required:
* HTML level change to prevent input boxes from going negative. This can be achieved by modifying attributes for the <input> element.
* Backend level change to ensure that data sent by the user is valid and positive. This can be achieved by filtering inputs prior to accepting them and inserting them into the database, and returning an appropriate error when needed.

**Comment by braughtg** [comment]
Nice bug report.  This identifies the same issue at #333, which also highlights an issue with decimal values for some fields.  This issue is being closed but will be referenced from that one.
