### ISSUE TITLE
DateSelectionComponent Updates

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#351]
The DateSelectionComponent (in farmdata2_modules/fd2_tabs/resources) should be updated so that its behavior is similar to that of the DropDownWIthAllComponent.  Specifically it should:
- Emit a date-changed event in the mounted hook so that the containing page is notified of the initial value if one is provided as a static prop.
- Add a watch for the defaultDate prop so that if it is bound in the page and changed then the date displayed in the component will change as well.
- Change the name of he defaultDate prop to be setDate to be more semantically accurate.
- Update all places where the DateSelectionComponent is used to use the new prop name.
  - FieldKit -> SeedingInput
  - BarnKit -> SeedingReport
  - Example -> UI
  - DateSelectionComponent.spec.js
  - Others?
- Update the README.md in the resources folder to match the changes to the component.

See #350 for how changes were made to the DropDownWithAllComponent.

**Comment by JingyuMarcelLee** [comment]
I will work on this issue
