### ISSUE TITLE
DateRangeSelectionComponent Updates

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#352]
The DateRangeSelectionComponent (in farmdata2_modules/fd2_tabs/resources) should be updated to have behavior similar to the DateSelectionComponent:
- Changing the props cause the displayed dates to update.
- Events emitted in mounted hook for initial values.
- Prop names changed from "default" to more semantically meaningful names.
- All instances of use of DateRangeSelectionComponent should be updated to use new prop names.
- Update associated component tests and UI example page and tests.
- Update the documentation in the README.md in resources.

Depends on #351 being completed first.

See:
- #350 for how the DropDownWithAllComponent was changed.
- #351 for how the DateRangeSelectionComponent is to be changed.

**Comment by JingyuMarcelLee** [comment]
I will work on this
