### ISSUE TITLE
CustomTableComponent Should Respond to Prop Changes

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#357]
The CustomTableComponent (in farmdata2_modules/fd2_tabs/resources) should be updated so that changing the visibleColumns, canEdit, canDelete, headers props cause table to update as appropriate.
- Update associated component tests.
- Expand the UI example page and tests to demonstrate some of the capabilities (e.g. showing and hiding a column)
- Update the documentation in the README.md in resources.

See:
- #350 for how the DropDownWithAllComponent was changed to respond to prop changes.

**Comment by JingyuMarcelLee** [comment]
I will work on this issue

**Comment by JingyuMarcelLee** [comment]
For now, we will just watch the visibleColumns prop changes.
