### ISSUE TITLE
Standard Error Handling for API Request Failure

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#360]
There should be a standard UI/UX approach to handling API request failures.  All API requests are done via functions (e.g. getAllPages, deleteRecord) in the FarmOSAPI.js library.  All of these functions return a promise that is accepted if the request succeeds and is rejected if the request fails. Thus they are called in a standard way:
```
getAllPages(...)
.then((resp) => { ... handle the response ... }
.catch(err) => { ... deal with an error ... }
```
Currently there is little to no error handling in the FD2 Example, FieldKit -> Seeding Input or BarnKit -> Seeding Report tabs.

TODO:
* [ ] An example should be built and tested on the UI sub-tab of the FD2 Example tab.
* [ ] The approach should be added into all of the API calls on FieldKit tab with tests.
* [ ] The approach should be added into all of the API calls on BarnKit tab with tests.
* [ ] The approach should be added into all of the API calls on FD2 Config tab with tests.

**Comment by braughtg** [comment]
An error banner stating "Error Processing Request.  This may be an intermittent network issue.  Please try again later." should be displayed for several seconds.  This will be similar to the confirm or cancel messages that are displayed by the SeeingInput page in the fd2_field_kit tab.

**Comment by FutzMonitor** [comment]
I will be tackling this issue.

**Comment by FutzMonitor** [comment]
Per Marcel and my conversation, we don't believe making the alert banner a component is beneficial for the project at large. The bootstrap element has pretty detailed documentation online already so making that into a component is pretty redundant and just adds unnecessary files to the project. The only potential benefit is that it makes it more _readable_ to other devs but, like I mentioned, documentation for this bootstrap feature already exists online.
