### ISSUE TITLE
Refactor Test for Seeding Report Page

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#367]
The tests in seedingReport.spec.js need to be refactored.  They have fallen out of date with the current state of development and have structural issues that cause intermittent 403 errors.  Some of the issues to address:
* Can better use the data-cy properties for the custom table.
* Structure tests as in api.spec.js in the fd2_example module to avoid 403 errors.

Related to #295, #296, #303 which have all been closed as consolidated into this issue.

**Comment by FutzMonitor** [comment]
I'll be tackling this issue.
