### ISSUE TITLE
Add Transplanting Report to the Barn Kit Tab

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#415]
A report can be generated showing crops that have been transplanted from a greenhouse to a field.

The functionality of the FarmData2 Transplanting Report will be similar to the Transplanting Report in the original FarmData, which can be seen here:

https://farmdata.dickinson.edu/Seeding/transplantReport.php?tab=seeding:transplant:transplant_report

In FarmData2 this Transplanting Report will appear in the Barn Kit tab and will allow the user to generate a report that displays information about the requested transplanting events. When generating and displaying this report, the style and user experience should be similar to:
* The examples that appear in the FD2 Example tabs
  * Their defining code is in the html files in the directory: farmdata2_modules/fd2_tabs/fd2_example
* The Seeding Report form that appears in the Barn Kit.
  * Its defining code is in the file: farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html

Data Model Notes:
* All Transplanting Logs have a Planting Asset associated with them.
  * The Planting Asset represents the crop that was transplanted.
  * There will also be a Seeding Log that represents the original action of planting the crop in the tray.

Information about the Tray Seeding Logs, Transplanting Logs and Planting Assets:
* General documentation for the sample database: https://github.com/DickinsonCollege/FarmData2/tree/main/docker/sampleDB
  * API Calls in that document show how to retrieve existing logs and assets that can be used to understand the JSON structures and their contents.
* The JSON Structures used to create the Logs and Assets in the sample database can be found in the python files in the docker/sampleDB directory:
  * The JSON structure for a Tray Seeding Log and its associated Planting Asset can be found in the file: docker/sampleDB/addTraySeedings.py
  * The JSON structure for a Transplanting Log and the process of creating one can be found in the file: docker/sampleDB/addTransplantings.py
* Information about the API calls used to create Logs and Assets using the JSON structures can be found:
  * In the file: docker/sampleDB/utils.py
  * In section of CONTRIBUTING.md that points to the FarmOS API documentation.

**Comment by johnmaccormick** [comment]
If you get a login error at the first link above, you need to first visit [https://farmdata.dickinson.edu/guest.php](https://farmdata.dickinson.edu/guest.php) to log in as a guest.

**Comment by braughtg** [comment]
Closed as the course associated with this issue has concluded.  It will be preserved in the project history as a basis for implementation of this feature in the future.

**Comment by FutzMonitor** [comment]
I will be tackling this issue.
