### ISSUE TITLE
Links to FarmOS API Need to Point to v1

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#448]
A number of links to the farmOS API (e.g. on CONTRIBUTING.md and ONBOARDING.md) point to the latest version of the farmOS API.  FarmData2 is currently using version 1 of the farmOS API and thus all links should point to that one.  The correct link appears in the FarmOS API section of the ONBOARDING.md file.   **All documentation should be searched for links to the new API and any found should be replaced with a link to the v1 API documentation.**

- Incorrect API link: https://farmos.org/development/api/
- Correct V1 API link: https://v1.farmos.org/development/api/

**Comment by ezinneanne** [comment]
**Hello, can I be assigned to this**

**Comment by braughtg** [comment]
Yes.  Thanks for asking!  Just ask if you have any questions.
