### ISSUE TITLE
Add Zulip to README as discussion platform for FarmData2

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#47]
This would include establishing the community communication channels for synchronous and asynchronous communication. There should be a forum for asynchronous questions to the community at a minimum.  What other channels would we like? Would it make sense to have a live forum in something like discord where people can come on the spur of the moment and talk to others? Or maybe a place where meetings could be scheduled and held rather than expecting someone to always be there?  Researching the range of things done by other projects would be valuable here.  We need something that would be responsive to those coming to the community without being a large burden on the (currently) small number of core community members.

**Comment by amelia291** [comment]
I think a Discord channel is not necessary since the scope of the project is quite small. If the Discord channel is very quiet, it might discourage people from contributing in general.

**Comment by Batese2001** [comment]
I actually think that discord is a great idea, but teams may work just as well if not better for what we want. I think discord has a tendency to be more informal (from my experience) while teams offers much the same features but with an added professionalism.

**Comment by zolboo1024** [comment]
I also think this is a great idea. When choosing which FOSS project to work on this year, whether the project has an established communication channel such as Discord or Slack was a huge contributing factor. I think it makes the community warmer and more welcoming and therefore, it will likely draw more people in.

**Comment by miyu386** [comment]
Personally, I do not use discord very often and am not too familiar with the features. I'm afraid there may be others who are also not too fond of it. A more general forum would probably be good for now.

**Comment by egorovak** [comment]
I agree with the comments above about quiet open chat being discouraging but I also never used discord and not sure how it works (whether you could see the channels without being added to the group). One comment mentioned using a more general chat and I think it might be a good idea but I do not expect discord being much different from Slack or Teams so at the end of the day it is just important to create some space for communication and question discussion with multiple channels.

**Comment by braughtg** [comment]
Element or riot seems like another good choice to explore:
- https://element.io/

**Comment by braughtg** [comment]
Zulip has been selected as the discussion platform.  They provided a sponsorship of a free standard cloud hosting for https://farmdata2.zulipchat.com/

An acknowledgement should be added to the README for this sponsorship.

**Comment by braughtg** [comment]
Closed by #88
