### ISSUE TITLE
Seeding Report UI Design

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#471]
The Seeding Report UI should be polished and refined.  This should include:
* ~~Aligning the date fields, and fixing them to be the same size.~~
* "Type Of Seeding" -> "Seeding Type"
* Making table headings consistent:
  * Date, Crop, Area
  * "Tray/Direct" -> "Seeding"
  * "Num Workers" -> Workers
* Fill "Seeding" Column with just "Tray" or "Direct"  (drop the word "Seedings")
* Swap order of "Hours" and "Workers"
  * ~~Check if hours is totaled across workers or if it is per worker!~~
* ~~Adjust width of date column so that dates appears on on line~~

**Comment by FutzMonitor** [comment]
I will be tackling this issue.

**Comment by braughtg** [comment]
In addition, there are different columns displayed when the report is filtered by tray seeding or direct seeding.  The following revisions can be made to those views:

* For Tray Seeding modify the column headings
  * Tray Seeds -> Seeds
  * # ot Trays -> Trays
  * Cells per Tray -> Cells/Tray
  
* For Direct Seedings modify the column heading:
  * Row/Bed -> Rows/Bed

**Comment by braughtg** [comment]
One other issue with the report is that the reporting of Hours in the Hours column should be rounded to two decimal places.  To see the issue: 
* Enter a seeding log with 3 workers for 30 minutes
* Generate a report
* The Hours column contains 0.5100000000000001

The hours values should be rounded to 2 decimal places for all cells.

**Comment by braughtg** [comment]
Also check to ensure that the Direct Seeding Summary or the Tray Seeding Summary displays an appropriate message when "All" seedings are displayed but there are no seedings of the type (i.e. no Direct Seedings).  This likely has to do with a v-if that is checking the contents of the "Tray/Direct" column, which used to say "Direct Seedings" or "Tray Seedings" and now says only "Direct" or "Tray" as requested above.

**Comment by braughtg** [comment]
One additional small change.  Reorder the columns for Rows/Bed, Row Feet, Bed Feet so that they appear in the order:  Row Feet, Bed Feet, Rows/Bed.
