### ISSUE TITLE
Seeding Report: Simple and Detailed Views

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#479]
The columns displayed in the seeding report should be dynamic based on the type of device the user is using.  There should be two modes, simple and detailed.  A drop down should be added to the filters to the filters in the page to switch between the two modes. 

This may require altering the CustomTableComponent component to watch for changes in the displayed columns. The essential columns that should be displayed are:

  - Date 
  - Crop
  - Area
  - Seeding
  - Row Feet
  - Bed Feet
  - Row/Bed

In the simple view mode (the default view on mobile), options other than those listed above should be hidden. Once the user switches to the detailed view mode (using either dropdown, button, or checkbox), other columns, such as the comment, should be displayed. 

Some unanswered questions related to this issue:

  - If the default view mode for the desktop is the detailed view, should we allow users to switch to the simple view? Would this be necessary?
  - What would be the best method for users to choose which view they want? (dropdown, button, checkbox...etc.)
  - Do we need to include the filtering feature directly on the web version of the report if the report can be exported and the user can filter using excel?

There should be new testing methods in the existing cypress file corresponding to the component to test the changes.

**Comment by braughtg** [comment]
> If the default view mode for the desktop is the detailed view, should we allow users to switch to the simple view? Would this be necessary?
* yes the drop down should be displayed on the desktop version as well. 

> What would be the best method for users to choose which view they want? (dropdown, button, checkbox...etc.)
* a dropdown to be consistent with other UI filters seems like the best choice. But if there are other proposals you like, sketch them out below and it can be discussed. 

> Do we need to include the filtering feature directly on the web version of the report if the report can be exported and the user can filter using excel?
* Yes it should be included. Seems like the right approach for consistency and flexibility. It may be nice to just see the simple report without exporting.

**Comment by JingyuMarcelLee** [comment]
I will work on this
