### ISSUE TITLE
Seeding Input: Labor Section Text Missing Plural

### ISSUE THREAD

**Issue by FutzMonitor** [DickinsonCollege/FarmData2#481]
Currently the language in the Seeding Input's "Labor" section is awkward because it has no plural. 
In order to see this issue, please follow these steps: 

In the FarmData homepage
1. Visit FieldKit tab.
2. Visit the Seeding Input sub-tab.
3. Scroll down, and you will see the awkward language under 'Labor' in the Seeding Input form.

![issueImg](https://user-images.githubusercontent.com/31524934/173846905-51df745b-6ad1-4a3c-bba5-0e1173eba5d7.png)

Desired results: 
Fixing the awkwardness by adding an '(s)' to "worker" should get the job done. This is what a desired fix would look like:

![resolvedImg](https://user-images.githubusercontent.com/31524934/173847430-68568f06-7fcf-4aef-92b5-96a44c2acc93.png)

**Comment by msaadm** [comment]
Hey @FutzMonitor, 
I am new to contributing to Open source, created the following PR, to fix the given issue.
#488 Fixed 'Seeding Input: Labor Section Text Missing Plural' 

Kindly accept my PR or guide me if something else is needed.

**Comment by braughtg** [comment]
@msaadm Welcome to the FarmData2 community!  Thank you for your contribution.  Have a look around and see if there are other things you'd be interested in in our project, we'll be happy to help.  Feel free to get in touch through our Zulip channel as well if you have questions.

I'll review your PR in a few moments.
