### ISSUE TITLE
DateRangeSelectionComponent: Add watched disabled prop

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#491]
The DateRangeSelectionComponent should have a prop named disabled that is watched and controls whether the date element contained in the component has the disabled attribute or not. This will be useful when a user has clicked submit for a form and then needs to Confirm or Cancel the submission. After clicking the Submit button, all fields in the form will be disabled so that they cannot be edited further (unless the user cancels the submission).

Additional component tests should be added to verify that this functionality works.

Past conversations suggested using the readonly attribute. But the Select element does not have a readonly attribute, so disabled will be used on all components for consistency.

**Comment by JingyuMarcelLee** [comment]
I will work on this with #490 and #489. All changes will submitted with on #494
