### ISSUE TITLE
UI Examples Tab: Add example of the RegExInputComponent

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#501]
Add an example of using the RegExInputComonent to the UI tab in the FD2 Examples tab. The example should:
* include a regular expression that only allows some format of input (e.g. positive integers). 
* display the events that are emitted in the page (similar to how other components display values from emitted events)
* include a button that disables/enables the field using its prop.
* include a button that sets the value of the field using its prop.

Cypress tests should be added to UI.spec.js to test the added functionality.

**Comment by FutzMonitor** [comment]
I will be tackling this issue.
