### ISSUE TITLE
Integrate Configuration into Seeding Input Page

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#519]
Once #515 is complete the Seeding Input page must be modified to require, make optional or hide the labor input fields based upon the `labor` configuration setting.

Appropriate tests should be added to the e2e tests for the Seeding Input page.  These can use the `setConfiguration` function in the `FarmOSAPI.js` library to set the configuration option and then check the visibility and behavior (required/optional) of the labor input elements.

**Comment by JingyuMarcelLee** [comment]
I will work on this.
