### ISSUE TITLE
Add image/gif of demo

### ISSUE THREAD

**Issue by boosungkim** [DickinsonCollege/FarmData2#52]
I noticed that other open source projects tend to have some sort of image or gif of the demo in their README or website. I think adding some sort of visual for this GitHub project may be helpful for newcomers in understanding what this project exactly does.

**Comment by hantrinh13** [comment]
I agree! I think creating a gif by using [ScreenToGif](https://github.com/NickeManarin/ScreenToGif) (for Windows) or [Peek](https://github.com/phw/peek) (Linux) is a good idea to help new developers and users have a sense of what this project looks like and does.
