### ISSUE TITLE
Integrate Configuration into the Seeding Report Page

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#520]
Once #515 is complete the Seeding Report page must be modified to display or hide the labor columns based upon the labor configuration setting.  If labor is required or optional the columns should be displayed. If labor is hidden then the columns should not be shown.

Appropriate tests should be added to the e2e tests for the Seeding Report.  These can use the `setConfiguration` function in the `FarmOSAPI.js` library to set the configuration option and then check the column visibility.

**Comment by JingyuMarcelLee** [comment]
I am working on this
