### ISSUE TITLE
CustomTableComponent Refactoring

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#530]
The CustomTableComponent should include the ability to specify buttons to appear in the table. These will be like the Edit/Delete buttons but will allow developers to add additional buttons that perform custom actions.  Two possible use cases include:
* Adding a "Transplant" button to a table in the Transplanting Log page that allows the user to click the button on a row to pre-populate a transplant input form for creating the transplanting log.
* A similar feature would also be useful for the Harvest Log page.

**Comment by braughtg** [comment]
One way to implement this would be to revise the use of the Input Type, Is Visible and Headers arrays to instead take one prop that has an array of objects containing the information about the column.  This would allow that object to also contain information about buttons that should be included in the table (e.g. Transplant) and the function to be called if the button is clicked.

**Comment by braughtg** [comment]
More details on a possible refactoring:
* The following props should be combined into a single prop named `columns` that becomes an array of objects instead of an array of values:
  * `headers`
  * `visibleColumns`
  * `inputOptions`
* An object in the `columns` prop will have a format like:
```
{
  "header": "A String",
  "visible": <true or false>,
  "inputType": {... see below ...},
}
```

The `inputTypes` will be specified by an object as follows:
* `no input`: `{"type": "no-input"}`
* `text`: `{"type": "text"}`
* `dropdown`: `{"type": "dropdown", "value": ["option one", "option two", "option three"]}`
* `date`: `{"type": "date"}`
* `regex`: `{"type": "regex", "value": "<a regular expression>"}` (replaces the `number` input type.)
* `button`: `{"type": "button", "value": "<a bootstrap glyphicon>", "event": "<a string>"}`

Note: The only the relevant properties will need to be specified.  So if the `inputType` is `date` or `text` then the `value` and/or `event` properties would not be specified.

If the `inputType` is `button`:
* The `value` entry will specify a bootstrap glyphicon to be displayed in the column (see Edit/Delete/Save/Cancel for examples).
* When the button is clicked the specified `event` will be emitted.
* The `id` of the `row` associated with the clicked button will be the payload of the event (see the code for deleting a row for an example of emitting the event with the `id` as a payload).

If there is an `inputType` of `regex`:
* The `save` button should be disabled unless the value in the field is valid according to the specified regular expression.

For now, editing and deleting of rows will remain an internal part of the component due to the complexities of changing buttons from edit/delete to save/cancel, etc.

An example of how a table might be created with the refactored component might look like the following:
```
<custom-table csv-name="example" :rows="tableRows" :columns="tableCols" @my-event="myHandler">
</custom-table>
```
The vue data object would then contain properties for `tableRows` and `tableCols` and a method for `myHandler`.  For example:
```
...
data: {
  tableCols: [ 
    { "header": "Crop", 
       "visible": true,
       "inputType": {"type": "dropdown", "value": ["CORN", "BEANS", "PEAS"]},
    },
    {  "header": "Transplant", 
       "visible": true,
       "inputType": {"type": "button", "value": "glyphicon glyphicon-random", "event": "my-event"},
    },
  },
  tableRows: [
    {id: 1, data: ['CORN', 'glyphicon glyphicon-random']},
    {id: 2, data: ['BEANS', 'glyphicon glyphicon-random']},
  ].
},
methods: {
  myHandler: function(rowID) {
    ... handle the my-event event from the button ...
  },
  ...
```

There will be a few rippling changes that will also need to be addressed with this change:
* The table in the UI example page will need to be updated.  This will be a good place to start and to use as a test of the changes.  It would be good to add a `button` column to that table that does something simple like displays an alert when the button is clicked.
* The SeedingReport page will need to have its table updated to use the refactored design.
* The TransplantingReport page (when finished) will need to have its table updated to use the refactored design.

**Comment by FutzMonitor** [comment]
I'll being tackling this issue.

**Comment by FutzMonitor** [comment]
On top of the developer's ability to select the bootstrap icon for the button, I think it's worthwhile to allow them to also add the type of color they would like the button to be to add some variety. It would look something like this: 

```
{"header": 'Clone',   // Name of the header for the button (e.g. this button clones the row)
    "visible": true,        // Is this column visible 
    "inputType": {
        'type': 'button', 'value': 'glyphicon glyphicon-asterisk',   // Type of icon for the button  
        'box': 'table-button btn btn-warning'}},                     // Type of button color background
}
```
I added this in the latest commit, and it works without any problem.

**Comment by FutzMonitor** [comment]
In addition to the details provided above: 

* Custom buttons should no longer be part of the table portion of the component but located on the top right-hand side of the table. If a dev creates a custom button then a checkbox column should be rendered on the leftmost side of the table (separate from the current *new* boolean input type) which controls which rows will be affected by the events of the custom buttons. In the case where there isn't any row selected, the custom buttons are disabled and are not clickable. To this end, I would recommend the creation of the following prop: 
  
  * `customButtons`

* This would be an array of objects, similar to `columns`, with the following structure:
```
{
  [
    "name": "A String",     // Used for the button's hover tip
    "icon": "A String",     // Used for the button's icon
    "color: "A String",     // Used for the button's color
    "event": "A String"    // Used for the button's event
  ]
  ...
}
```
* This has unique implications for the export button that shall be explored in a later issue. 

Additionally, the `selectAllEvent` should only be altering checkbox values for rows that are currently visible to the user. It would be really bad if the select all button happened to delete data that the user didn't intend to delete from the database.

**Comment by FutzMonitor** [comment]
Some clarifications about the new `boolean` input type and the checkboxes that will be rendered on the leftmost column whenever there are custom buttons or delete is enabled: 

1. The ` boolean` input type will only be interactable when that row is being edited. Furthermore, the "select all" option for the header will be removed because it introduces functionality discrepancies where the user can change the value for multiple checkboxes when they shouldn't be editable unless you are specifically editing that one row. 
2. The leftmost column checkboxes that will be connected with the custom buttons, delete, and possible the export csv functionality (see #571) will be interactable at all times unless the row is being edited. It will have a select all option which allows you to select all the rows. If there are no selections, then the custom, delete, and potentially csv buttons will be disabled.

**Comment by FutzMonitor** [comment]
I'd like to clarify a misunderstanding I had about the `CustomTableComponent`. The component does not assign the the ID values for the rows. Those values come from the rows themselves and are fed to the component. You can see it clear as day here in the UI page [[here](https://github.com/DickinsonCollege/FarmData2/blob/main/farmdata2_modules/fd2_tabs/fd2_example/ui.html#L235)].  

You can also see a more practical example of how ID's are assigned by viewing the Seeding Report page [[here](https://github.com/DickinsonCollege/FarmData2/blob/main/farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html#L393)]. 

As you can see, those IDs are simply fed to the table not assigned by it. Just wanted to make this clarification due a confusion I caused in a belief that the table created this value for the rows.
