### ISSUE TITLE
Seeding/Transplanting Reports Default Start Date

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#539]
The default start date for generating seeding reports should be the first day of the current year.

![image](https://user-images.githubusercontent.com/16962482/179606615-209767d8-02ed-40d8-8dcc-fdc4c3499f9f.png)

To reproduce:
1. Click the BarnKit tab.
2. Click the Seeding Report sub-tab.
3. Examine the Start Date.

**Comment by braughtg** [comment]
The default date that is displayed will be set within the `seedingReport.html` page in the `farmdata2_modules/fd2_tabs/fd2_barn_kit` folder.

When the default date is updated the cypress tests in `seedingReport.spec.js` should be updated to test that the date is correct.  The date should not be hard coded so that the test will continue to work into the future.

**Comment by braughtg** [comment]
The fix for this should also be applied to the transplanting report.

**Comment by FutzMonitor** [comment]
I can tackle this issue.
