### ISSUE TITLE
Seeding Input Form: Optional Labor Data

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#541]
When labor data is configure as optional, the seeding input form should require either:
* Both "workers" or "hours/minutes" are specified 
Or
* Neither "workers" nor "hours/minutes" are specified.

This prevents situations where we have 0 workers for 5 hours or 3 workers for 0 hours.

**Comment by JingyuMarcelLee** [comment]
I will work on this issue
