### ISSUE TITLE
Add Regular Expression Constants

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#548]
Regular expressions are used with the `RegexInputComponent` (in `farmdata2_modules/fd2_tabs/resources`) to ensure that data entered is valid for the purpose (e.g. positive integer or decimal, etc).  When this component is used in a page the regular expression to be used needs to be specified.  This leads to the same regular expression being written repeatedly in multiple locations. It would be preferable to have a single location where commonly used regular expressions can be defined once and then used wherever needed.  See the `SeedingReport.html` (in `farmdata2_modules/fd2_barn_kit`) for an example of where this would be useful.

**Comment by JingyuMarcelLee** [comment]
I will work on this.

**Comment by JingyuMarcelLee** [comment]
Closed with #553
