### ISSUE TITLE
Transplanting Report: Editing Transplanting Logs Does not Update them in the Backend

### ISSUE THREAD

**Issue by FutzMonitor** [DickinsonCollege/FarmData2#562]
## Current Behavior ##
1. Visit the Transplanting Sub-tab under the Barnkit module. 
2. Generate a report from 05/04/2020 to 05/04/2020.
3. Click the edit button and change the date, crop, area, trays, and user then click the save button.
4. Visit Hoppscotch and using the GET function enter this link in the URL: `http://localhost/log/1183`
5. Verify that the data that you changed inside of the Transplanting Report has not changed (date changes timestamp, area changes can be seen inside of movement, crop changes can be see at the bottom with the data crop_tid, and user can be found inside of the log owner array). 

![image](https://user-images.githubusercontent.com/31524934/181109348-c29c5a9d-d96d-401f-973a-b18baf89a67f.png)
*Changes on the frontend are visible*

![image](https://user-images.githubusercontent.com/31524934/181109557-9566d574-050a-4e38-8d73-348349e9d9ca.png)
*Changes have not actually been made in the backend (trays for example is still 8 despite being 60 in the report)*

## Desired Behavior ##
The desired behavior would be that the user can change the date, crop, area, trays, and user and those changes are actually reflected in the backend. Currently the user is allowed to change the value inside of _Bed Feet_, but it might not be worth allowing them to do this because the backend doesn't have a quantity for this anyway. Additionally, changing Row Feet recalculates Bed Feet anyway. It would be worth testing if the transplanting report, after fixing the backend updates, suffers from similar bugs that the Seeding Report suffers from. This includes:
1. Changing an area and a quantity causes a 422 status code
2.  Making sure that changing the quantity along with date, crop, area, comments, and user actually updates the frontend appropriately (Seeding Report had an issue where frontend was not being updated correctly when a quantity and another element were changed at the same time)

The Cypress e2e file for this should also be updated with a more rigorous testing suite. 

## Afterword
Pull request #551 is a good place to look into for people seeking to solve this issue. It confronts the exact same issue except for the Seeding Report.

**Comment by FutzMonitor** [comment]
Since all the e2e tests have broken since the vnc update should this PR wait until #578 is completed?

**Comment by braughtg** [comment]
> Since all the e2e tests have broken since the vnc update should this issue wait until #578 is completed?

I think these two could be done in either order.

**Comment by FutzMonitor** [comment]
I can tackle this issue.
