### ISSUE TITLE
Selective Launch of Containers

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#575]
Modify the fd2-up.bash script so that FarmData2 can be launched with or without the development environment container and/or the phpmyadmin containers.  Not all uses will need the phpmyadmin container and many may not want the dev container running all of the time (e.g. just using it for testing).  So it would be nice to be able to start those separately.  Maybe have the dev container start by default and the phpmyadmin container only start if requested? Then also be able to take either of those up or down independently of the other containers?

**Comment by braughtg** [comment]
The likely solution here is to create a profiles in `docker/docker-compose.yaml` that allow the `dev` and `phpmyadmin` containers to be started only when their profile is included in the up command.  Then modify the `fd2-up.bash` script to accept flags such as `--no-dev` and `--no-php-admin` that prevent those containers from starting.

**Comment by FutzMonitor** [comment]
This is a bit out of my element, but I can attempt to tackle this one.

**Comment by FutzMonitor** [comment]
Should developers be allowed to prevent both php-admin and the dev container from launching?

**Comment by braughtg** [comment]
> Should developers be allowed to prevent both php-admin and the dev container from launching?

Yes.  They could use both flags to do this.
