### ISSUE TITLE
Dev Container Fails to Launch Unless Removed from Local Storage

### ISSUE THREAD

**Issue by JingyuMarcelLee** [DickinsonCollege/FarmData2#584]
## Description of the Issue
The dev container fails to launch with an error message when it is launched without having it removed from the local storage after the previous launch. 
![image](https://user-images.githubusercontent.com/46755208/205471476-31d8f536-471a-4323-a08e-0bfc8edebfba.png)

It runs successfully if the container is removed from the local storage after the previous run (by manually deleting the container from the docker desktop or running the `docker rm` command).

## Steps to Reproduce

1. Run Farmdata with `./fd2-up.bash` inside the docker directory. 
2. Farmdata should launch without error as the dev container did not exist in the local storage when Farmdata was launched for the first time. 
3. Stop Farmdata with `./fd2-down.bash`. All containers should be removed except the dev container as the fd2-down.bash script does not remove the dev container.  
![image](https://user-images.githubusercontent.com/46755208/205471724-b9206de5-7910-433b-be01-dfef42641c5d.png)
4. Relaunch Farmdata `./fd2-up.bash`. The dev container fails to launch with error messages. 
![image](https://user-images.githubusercontent.com/46755208/205471476-31d8f536-471a-4323-a08e-0bfc8edebfba.png)
## Suggested Solution

Temporary solution: remove the dev container every time by including `docker rm fd2_dev` in the fd2-down.bash script file.

**Comment by FutzMonitor** [comment]
I am running into a similar issue at times, but I unfortunately do not have specific steps for recreating the bug. The only things I've noticed, on my end, is that quick uses of the `docker exec -it fd2_farmdata2 drush cc all` command eventually leads to the Vue tools extension on FireFox acting buggy. When you notice this and take down the container, trying to bring it back up produces the following error, similar to the one commented by Marcel. 

![image](https://user-images.githubusercontent.com/31524934/206220396-d3673638-0468-40df-a7be-a2f78246e8f4.png)

I used to remove everything to get it to work, but I tried Marcel's solution and that also does the trick.

**Comment by braughtg** [comment]
@FutzMonitor @JingyuMarcelLee 

There may be a permission error at work here.

Can you check the group, owner and permissions of the `~/.fd2gids` directory and its contents in your WSL?  Please post the output of the command when run from your WSL shell:
* `ls -al ~/.fd2gids/`

**Comment by JingyuMarcelLee** [comment]
> @FutzMonitor @JingyuMarcelLee
> 
> There may be a permission error at work here.
> 
> Can you check the group, owner and permissions of the `~/.fd2gids` directory and its contents in your WSL? Please post the output of the command when run from your WSL shell:
> 
> * `ls -al ~/.fd2gids/`

Below is the result @braughtg :
![image](https://user-images.githubusercontent.com/46755208/206879601-e6ecec09-7944-40a3-886c-b0cdfd946f0b.png)

**Comment by FutzMonitor** [comment]
> @FutzMonitor @JingyuMarcelLee
> 
> There may be a permission error at work here.
> 
> Can you check the group, owner and permissions of the `~/.fd2gids` directory and its contents in your WSL? Please post the output of the command when run from your WSL shell:
> 
> * `ls -al ~/.fd2gids/`

Below is my result @braughtg: 
![image](https://user-images.githubusercontent.com/31524934/206887128-e0c38021-3879-4f83-8103-74ff7d28b0ce.png)

**Comment by FutzMonitor** [comment]
I also believe this is a fine solution for now since most user will probably be using their home OS to test and interact with FD2 versus the dev container.
