### ISSUE TITLE
Table Export includes `-` characters at end of Comments field.

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#589]
When a report is exported using the export button, values in the comments column include extra `-` characters at the end of the comment.  

**To Replicate**
1. Go to BarnKit / Seeding Report
2. Search for 05/01/2020 - 05/05/2020
3. Click the Export Button above the table.
4. Open the resulting CSV file.
5. Observe the contents of the Comments Column
6. Note extra `-` that do not appear in the Comments column in the table itself in FarmData2.

**Comment by FutzMonitor** [comment]
I will be tackling this issue. I think I might close both this issue and #571 under the same PR since they both deal with the export button.

**Comment by braughtg** [comment]
> I might close both this issue and #571 under the same PR since they both deal with the export button.

Sounds good.  I'll assign #571 to you also.
