### ISSUE TITLE
Incorrect Regular Expression for Editing Hours in Seeding Report

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#590]
When editing a row in the seeding report the field for entering hours does not allow decimal values (e.g. 0.5 hours).  It allows only whole numbers (e.g. 2 hours).  The field should allow decimals to be entered.

**To Replicate**
1. Visit BarnKit / SeedingReport
2. Click the edit button beside any row.
3. Attempt to change the hours to a decimal value (e.g. 0.5).
4. Observe that the field turns red and the change cannot be saved.

**Comment by FutzMonitor** [comment]
I followed the steps and did not observe the behavior mentioned in this bug report. 
https://user-images.githubusercontent.com/31524934/209585951-48167768-7622-4e41-8aa3-5d95db354de3.mp4

**Comment by braughtg** [comment]
@FutzMonitor Agreed.  I do not see this issue now.  I'm not sure what I was seeing when I reported it.  Closing, but can reopen if the issue reappears.
