### ISSUE TITLE
Express.js Cutsom API Endpoint Documentation

### ISSUE THREAD

**Issue by JingyuMarcelLee** [DickinsonCollege/FarmData2#597]
Documentation is needed for the Express.js Custom API endpoint. To allow JSDOC to automatically create documentation for the API Endpoints, we should consider including a doc folder inside the farmdata2_api folder. ~~Also, the README.md file inside the docker folder should be updated so that it includes information regarding the Express.js docker image and container.~~

**Comment by JingyuMarcelLee** [comment]
README.md has already been updated at #568.

**Comment by braughtg** [comment]
We should consider using OpenAPI with JSDoc and Swagger for documenting the API itself for developers.  See:
* https://dev.to/kabartolo/how-to-document-an-express-api-with-swagger-ui-and-jsdoc-50do

Documentation for how to work on the API will be addressed as a part of #572.

**Comment by braughtg** [comment]
Use the following as a reference when naming endpoints:
* https://restfulapi.net/resource-naming/

**Comment by braughtg** [comment]
The plan at this point is to 
* build a spike outside of FarmData2 to test the Swagger documentation tools.  It will be integrated into the FarmData2 environment when we understand it.
* do a survey of the Seeding Report, Seeding Input, Transplanting Report and the FarmOSAPI.js files to understand all of the API calls that are being made.  Then use that survey to think about what "collections" of api endpoints we want to define for the farmdata2_api.
