### ISSUE TITLE
INSTALL.md for Mac OS Developers

### ISSUE THREAD

**Issue by megandalster** [DickinsonCollege/FarmData2#62]
The Developer Install instructions in INSTALL.md lead to a clean install on a Mac OS platform with Git, Docker, and docker-compose.  One major change to the INSTALL.md needs to be made for Mac OS developers:

In "Adding Customizations" sections 1 and 2, change "www-data:www-data" to "username:admin" (where username = the Mac OS user's name) in both places that call for setting the owner and group.

Another change needs to be made for all Developer Installs:

In "Bringing Up FarmOS" section 2, change "Click the User Accounts tab" to "Click the Privileges tab"

Overall, this document can use a careful edit, especially for line numbers.

**Comment by braughtg** [comment]
It would be ideal to test this out for clean installs on both Mac and Windows.  Then update the INSTALL.md file as appropriate. It may have separate sections for Mac/Windows, or maybe just notes at the appropriate steps where things differ.  

There should also be a process by which anytime a change is made to INSTALL.md tickets are posted for checking it on Mac/Windows/Linux to ensure that it is always up to date.

**Comment by braughtg** [comment]
Note: Currently working on a new, much simpler and cleaner, install process.  I will update INSTALL.md when it is complete.
