### ISSUE TITLE
Typo in clearDupalCache bash Alias in dev container

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#635]
In the `bash_aliases` file in `docker/dev` there is a typo in the definition of the `clearDrupalCache` command.

The command is currently declared as `clearDupalCache` (note the missing `r`).

The command should be declared as `clearDrupalCache`

To fix this:
* Edit the `bash_aliases` file.
* Rebuild the dev docker container to test it.
  * Note the name of the current dev image in Docker Desktop
  * Use `docker build` locally to create an image with exactly same name as the existing one.
* Use `./fd2-down.bash`
* Use `./fd2-up.bash` 
* Check that the `clearDrupalCache` command works in the dev environment.
* Make PR.
* The maintainers will rebuild the actual image using your fix and push it to Dockerhub.

**Comment by FutzMonitor** [comment]
I made sure to test this inside the dev container. This works now with the new `clearDrupalCache`.
