### ISSUE TITLE
Tray Seeding Summary: Improper results (NaN) 

### ISSUE THREAD

**Issue by ChloeHo12** [DickinsonCollege/FarmData2#644]

**Comment by FutzMonitor** [comment]
Hello @ChloeHo12, I see that you made the same issue on the [FarmData2-190WiD-S23](https://github.com/dickinson-comp190/FarmData2-190WiD-S23) at this [location](https://github.com/dickinson-comp190/FarmData2-190WiD-S23/issues/34). Could you kindly close this issue?
