### ISSUE TITLE
Dev Container: Bidirectional Clipboard 

### ISSUE THREAD

**Issue by FutzMonitor** [DickinsonCollege/FarmData2#648]
## Current Design
Currently the dev container doesn't support a bidirectional clipboard. So, anything copied from within the dev container can be pasted inside the docker container but not pasted outside into the host machine. The same runs true for the host machine, naturally anything copied in the host machine can be pasted in the host machine but cannot be pasted into the dev container because it doesn't have access to the host machine's clipboard. 

## Desired Design
Added functionality so that the dev container can have something within copied and pasted into the host machine. The same runs true for the host machine, developers should be permitted to copy something from their host machine and paste it into the dev container. 

Of course we can screenshot for the time being to report error outputs, but it's time consuming when we want to copy and paste a relatively long command from our host machine into the dev container. A work around is to simply work within the dev container and visit the sources we're copying and pasting from, but it would be convenient for those who use the dev container mainly for testing experimental features.

**Comment by braughtg** [comment]
When connecting to the dev container with a VNC Client (e.g. Tiger VNC) the clipboard is bi-directional and it is possible to copy and paste between the container and the host.  If you are using the noVNC client through a browser you have to use the noVNC clipboard to do this.  The noVNC clipboard is located in the little tools panel that pops out from the left of the window:

<img width="74" alt="image" src="https://user-images.githubusercontent.com/16962482/232472899-d990d126-255c-4539-9d96-7671210d54ab.png">

You can copy from the host and paste into that clipboard. That content will then be available for paste inside the container, and vice versa.  This is not the most convenient, but it is a limitation of using noVNC.  

I recommend using a VNC Client (e.g. TigerVNC) which supports full bi-directional copy and paste.
