### ISSUE TITLE
Divide FarmOSAPI Tests into smaller files.

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#651]
Break the tests here into smaller pieces with each being contained in its own file.  For example, the tests for getting maps should be broken out into `FarmOSAPI.maps.spec.js`. This will better allow developers to only run those tests that are being affected by current changes.  

The full `FarmOSAPI.spec.js` file should be examined and the exact division of the current tests into smaller files should be done based on the functionalities being tested.

**Comment by nguyenbanhducA1K51** [comment]
Hi! @braughtg  I would like to work on this issues. My strategy here is breakdown the `FarmOSAPI.spec.js` file into 4 smaller tests that is contained in a new API folder  in `./farmdata2_modules/resources`.
