### ISSUE TITLE
Dev Container VNC Server is slow to start

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#655]
When running `./fd2-up.bash` to start the development environment the `fd2_dev` container runs the VNC Server that is connected to in order to show the desktop environment.  It seems to take quite a while (20-30 seconds) after `./fd2-up.bash` reports that the Drupal cache has been cleared and that "FarmData2 started", before we can connect via VNC.  When you try to connect during this time, the VNC client just silently quits.

It would be good to be able to connect via VNC immediately after the "FarmData2 started" message.  It would be even better if the 20-30 second delay between clearing of the cache and connecting were eliminated.

This seems to have something to do with the dev container startup process.  Perhaps that can be streamlined or reordered?

**Comment by JingyuMarcelLee** [comment]
Will take a look at this and review the pr

**Comment by FutzMonitor** [comment]
I'll be reviewing the the PR for this issue.

**Comment by JingyuMarcelLee** [comment]
Tested PR. Dev environment started without issues on WSL2 w/ Docker desktop.
