### ISSUE TITLE
Seeding Report: Duplicates appearing in Crop Dropdown when editing a record

### ISSUE THREAD

**Issue by Shahir-47** [DickinsonCollege/FarmData2#656]
The Crop drop-down in the Seeding Report form contains duplicates. Each Crop should appear in this list only one time. 

![image](https://user-images.githubusercontent.com/98346408/236004036-cd90520a-52d2-4d66-9d66-daa075f2612b.png)
![image](https://user-images.githubusercontent.com/98346408/236004090-3761818a-9378-4594-a921-51577cbe52dd.png)

Steps to Reproduce

1. Clear browsing data
2. Visit the Seeding Report form
3. Click the edit button on any record
4. Observe that items are repeated twice

You can use Vue to clearly see that the computed method cropNameArray, which returns the list of crop names to the Crop drop-down menu, has a length of 222 items. There are only 111 crop names.
 
![image](https://user-images.githubusercontent.com/98346408/236008165-24868a90-0ed9-4f11-892f-3881e25d6f33.png)

 The cropNameArray is fed to the second column of the table as observed by the line of code below, which can be found at [https://github.com/DickinsonCollege/FarmData2/blob/main/farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.html](url) 

` {"header": 'Crop', "visible": true, "inputType" : {'type': 'dropdown', 'value': this.cropNameArray}} `

**Comment by johnmaccormick** [comment]
This issue was created in error and is being closed. Please could an admin permanently delete it? (@braughtg ??) thanks!
