### ISSUE TITLE
BarnKit Seeding Report Total Bed Feet Planted not rounded

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#657]
Sometimes the "Total Bed Feet Planted" value reported in the summary table at the bottom of a Seeding Report is not rounded.  This value should be rounded to the nearest integer.

**To Reproduce**
1. Open the BarnKit
2. Generate a report for the dates 05/01/2019 - 05/20/2019

**Observed Output**

![image](https://github.com/DickinsonCollege/FarmData2/assets/16962482/47206adb-5ec9-473f-afc6-53e22b554516)

**Desired Output**

The "Total Bed Feet Planted" should be an integer.

**Comment by braughtg** [comment]
Note that this appears to be being caused by some non-integer data for Bed Feet Planted in the database.  This can be seen by switching the report to show only Direct Seedding.  Then several rows of the Seeding Report contain non-integer values:

![image](https://github.com/DickinsonCollege/FarmData2/assets/16962482/45576031-6405-4e00-b7db-d25c76d6f54e)

This is likely due to a conversion from Row Feet in the original data when the sample database is created.  It could be fixed there, but regardless the UI code should round the result to the nearest integer.

**Comment by FutzMonitor** [comment]
I can tackle this issue. 

The reproduction directions are incorrect. That range does not include the logs that cause the issue. For the starter date, I used 04-01-2019 instead and that successfully reproduced the issue.
