### ISSUE TITLE
Issues that will be migrated from FD2school Repo

### ISSUE THREAD

**Issue by RolandLocke** [DickinsonCollege/FarmData2#662]
List of Issues that need to be migrated from the [FD2school](https://github.com/DickinsonCollege/FD2School-FarmData2) Repo:

- [x] [Updated documentation to account for extra blank spaces added in CustomTableComponent](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/239)
- [x] [Main fd2 tabs test](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/228)
- [x] [Testing the default values of the seeding report](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/227)
- [x] [BarnKit Subtab testing](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/219)
- [x] [FieldKit Tab: test for FieldKit Sub-Tabs](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/212)
- [x] [Create test file for the Seeding Input](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/211)
- [x] [Test Barn Kit Seeding Report columns by seeding type](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/210)
- [ ] (Will Not be Migrated) [Added cy.waitForPage() to dbtest testing examples](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/209)
- [x] [Seeding input: Tests for Submit Button Behavior](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/208)
- [ ] (Will Not be Migrated) [Added FD2 Example sub-tab for testing with database access](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/198)
- [x] [Testing Transplanting Report Defaults](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/197)
- [x] [Tested the Seeding Crop Filter](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/196)
- [x] [Testing Seeding Input Tray Seeding Defaults](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/194)
- [x] [Test Seeding Input Direct Seeding Defaults
](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/182)
- [x] [Tested Seeding Input Type Defaults](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/178)
- [x] [Initial Commit, adding seeding input data cypress test](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/175)
- [x] [Cypress Tests for seeding Input Labor Defaults](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/173)
- [ ] (Will Not be Migrated) [Activity02 fix](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/25)

**Comment by Foogabob** [comment]
@braughtg I don't know if I should Migrate [#25](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/25). In the Farmdata2School repo the commit doesn't appear in the logs.

Here are the logs closest to Feb 8, when the commit was pushed, but I don't see it. Are any of these the #25?

```
commit 64be3c243c63bf6341fa43d4673529066c25f284
Author: braughtg <braught@dickinson.edu>
Date:   Sat Feb 11 08:40:21 2023 -0500

    Fixed Q1 in FD2 School 03 Vue Data Binding.

commit 1e1badc45383fe968a7eb0563d8dd199d469fca1
Author: braughtg <braught@dickinson.edu>
Date:   Tue Feb 7 12:54:39 2023 -0500

    Fixed typos and formatting in FD2School activity 01

commit 5a4bcc7b1c3d7dafdc791b497ee0397713d855c7
Author: braughtg <braught@dickinson.edu>
Date:   Mon Feb 6 17:00:34 2023 -0500

    Removed review request question in FD2 school activity 02

commit 20cebefb656429953a4ce3ac0e3db8cd48a09160
Author: braughtg <braught@dickinson.edu>
Date:   Sat Feb 4 17:53:28 2023 -0500

    Fixed typos in FD2School Activity 03

commit 9569104335ba15c6ab74ac4b9071ea88b07febcd
Author: braughtg <braught@dickinson.edu>
Date:   Sat Feb 4 16:47:10 2023 -0500

    Corrected Field -> Area in HTML activity 02.

commit 79f2c7ea27c8863d405343c57575c0df29114f73
Author: braughtg <braught@dickinson.edu>
Date:   Sat Feb 4 15:48:57 2023 -0500

    Standardized on double quotes on activity 03

commit 08a643c7dc2f48393ed787d674fe77b06cf6e5ed
Author: braughtg <braught@dickinson.edu>
Date:   Fri Feb 3 16:17:09 2023 -0500

    Edits to FD2School activity 03

commit ce7531fdac5f7d076fd736b2f1f27aac05bb1d38
Author: braughtg <braught@dickinson.edu>
Date:   Fri Feb 3 15:56:42 2023 -0500

    Updates to FD2School activity 03

commit 2614919cb086942b981142dec17ffb4724357591
Author: braughtg <braught@dickinson.edu>
Date:   Fri Feb 3 15:55:47 2023 -0500

    Minor edits to activity 02

commit 939574115e5892459d6e317ac6b8ff273fbbd9f7
Author: braughtg <braught@dickinson.edu>
Date:   Mon Jan 30 14:17:31 2023 -0500

    Added linking to issue in PR to activity 02

commit 639b03c07841688d8b7d8f04bbf9b91df4e875d5
Author: braughtg <braught@dickinson.edu>
Date:   Sat Jan 28 12:08:15 2023 -0500

    Updated FD2School Activity 02

commit 06d624d56122cdb8238a1df651b5ed3e7c6d1232
Author: braught <braught@dickinson.edu>
Date:   Sat Jan 28 11:35:18 2023 -0500

    Updated link in FD2School info tab

commit f6c2d526e03c7ea3fe26800bf86565769beef381
Author: braughtg <braught@dickinson.edu>
Date:   Sat Jan 28 09:55:35 2023 -0500

    Updated FD2School Activity 02
```

**Comment by Foogabob** [comment]
The pull request: https://github.com/DickinsonCollege/FD2School-FarmData2/pull/209 is dependent on the issue: https://github.com/DickinsonCollege/FD2School-FarmData2/pull/198. Should I leave them as separate issues or combine them into one?

**Comment by braughtg** [comment]
This does not need to be migrated.

**Comment by braughtg** [comment]
> I don't know if I should Migrate [Activiy02 fix #25](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/25). In the Farmdata2School repo the commit doesn't appear in the logs.

This does not need to be migrated.

**Comment by braughtg** [comment]
> The pull request: [DickinsonCollege#209](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/209) is dependent on the issue: [DickinsonCollege#198](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/198). Should I leave them as separate issues or combine them into one?

Neither of these need to be migrated.

**Comment by braughtg** [comment]
@RolandLocke I'll have a look at these and try one in the next few days.
