### ISSUE TITLE
GitFlow link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#78]
Add a link to https://guides.github.com/introduction/flow/ to the discussion of GitFlow in the CONTRIBUTING document.  There is a link to the detailed version, this link is to a simpler, more concise explanation.  It may be useful to incorporate both in some way.

**Comment by 96RadhikaJadhav** [comment]
@braughtg  Can I work on the issue?

**Comment by braughtg** [comment]
@96RadhikaJadhav Yes, happy to have the help.  Please use the process outlined in CONTRIBUTING.md and submit a pull request.  I'll be happy to answer questions or discuss your proposed changes on the PR.

**Comment by 96RadhikaJadhav** [comment]
@braughtg One doubt here. Should we replace the existing link of the detailed version to the new link or should we just add this new link there keeping detailed one as it is?

**Comment by braughtg** [comment]
I propose the following:
- Take on the mindset of a new developer
- Review the two resources (new link, detailed version)
- Create a PR to propose a new sentence or two that fit with the tone of the document and will be informative and useful to new developers.

We can then discuss specifics based on your proposal.

**Comment by 96RadhikaJadhav** [comment]
Sure, will work on it.

**Comment by 96RadhikaJadhav** [comment]
@braughtg Created a PR. Could you please review it.
